name: hello world
on:
  push:
    branches: [master]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY='02/08/2023'" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
