name: hello world
on:
  push:
    branches: [master]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date + %d-%m-%Y)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
